routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Models\Slider;
use App\Models\Menu;
Auth::routes();

Route::get('/', function() {
	return view('frontend.homepage')
		->with('sliders',Slider::get())
		->with('menus', Menu::where('status', '=', '1')->limit(4)->orderBy('id', 'desc')
		->get());
})->name('frontend.home');

Route::get('/about',function() {
	return view('frontend.about');
})->name('frontend.about');

Route::get('/contact',function() {
	return view('frontend.contact');
})->name('frontend.contact');

Route::get('/menu',function(){
	$menu = Menu::where('status', '=', '1')->get();
	return view('frontend.menu')->with('menu',$menu);
})->name('frontend.menu');


Route::get('/product/{id}', 'frontendController@toDetails')->name('frontend.product');
Route::get('/menu/custom', 'frontendController@toCustom')->name('frontend.custom');
Route::post('/menu/custom/store', 'frontendController@storeCustom')->name('frontend.store.custom');

Route::get('/cartlist', 'frontendController@cartList')->name('frontend.cartlist');
Route::post('/cart', 'frontendController@addToCart')->name('frontend.add_to_cart');
Route::get('/deleteItem/{rowId}', 'frontendController@removeCart')->name('frontend.remove_cart');
Route::get('/checkout', 'frontendController@checkoutCart')->name('frontend.checkout');
Route::post('/checkout/store', 'frontendController@checkoutStore')->name('frontend.store.checkout');
Route::post('/updateCart', 'frontendController@updateCart')->name('frontend.update');
Route::get('/history', 'frontendController@toHistory')->name('frontend.history');
Route::get('/history/detail/{id}', 'frontendController@historyDetail')->name('frontend.history.detail');

Route::get('/logout','AdminController@logout')->name('logout');
Route::get('/image/{fileName}/{path}','SliderController@getFileByName');
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
	Route::get('/purchase/mark/{model}','PurchaseController@changeStatus');
	Route::get('/receipt','AdminController@goReceipt');
	Route::get('/payment','AdminController@payment');
	Route::get('/purchase/export','PurchaseController@exportData')->name('purchase.export');
	Route::get('/mark/{model}','AdminController@changeStatus');
	Route::get('/receipt/{model}','AdminController@getReceipt');
	Route::post('/menu/calculate','MenuController@calculate');
	Route::post('/dashboard/calculateMenu','AdminController@calculateMenu');
	Route::post('/dashboard/calculateCustom','AdminController@calculateCustom');
	Route::resource('/user', 'UserController');
	Route::resource('/category', 'CategoryController');
	Route::resource('/slider', 'SliderController');
	Route::resource('/food', 'FoodController');
	Route::resource('/menu', 'MenuController');
	Route::resource('/guest', 'GuestController');
	Route::resource('/purchase', 'PurchaseController');
	Route::resource('/custom', 'CustomController');
	Route::resource('/dashboard', 'AdminController');

	Route::group(['prefix' => 'datatable', 'middleware' => ['auth']], function () {
		Route::post('/user', 'UserController@dataTable')->name('user.list');
		Route::post('/category', 'CategoryController@dataTable')->name('category.list');
		Route::post('/slider', 'SliderController@dataTable')->name('slider.list');
		Route::post('/food', 'FoodController@dataTable')->name('food.list');
		Route::post('/menu', 'MenuController@dataTable')->name('menu.list');
		Route::post('/guest', 'GuestController@dataTable')->name('guest.list');
		Route::post('/purchase', 'PurchaseController@dataTable')->name('purchase.list');
		Route::post('/custom', 'CustomController@dataTable')->name('custom.list');
		Route::post('/dashboard', 'AdminController@dataTable')->name('dashboard.list');
	});
});

app/Models/Custom.php
<?php

namespace App\Models;

use App\Models\Base\BaseModel;
use App\Models\Food;
use App\Models\Purchase;
use Illuminate\Database\Eloquent\Model;

class Custom extends BaseModel
{
    protected $fillable = [
    	'total'
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    public function foods() {
    	return $this->belongsToMany(Food::class,'custom_foods')->withPivot('quantity', 'subtotal');
    }

    public function purchases() {
        return $this->belongsToMany(Purchase::class,'custom_purchases')->withPivot('quantity', 'subtotal');
    }
}

app/Http/Controllers/CustomController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\MasterController;
use App\Models\Food;
use App\Models\Custom;
use Illuminate\Http\Request;

class CustomController extends MasterController
{
    protected $show_view = 'admin.custom.index';
    protected $create_view = 'admin.custom.form';
    protected $edit_view = 'admin.custom.form';
    protected $route_bind_model = 'custom'; //Route Model Binding name in RouteServiceProvider
    protected $redirect_when_success = 'custom.index'; //Route Name
    protected $datatable_buttons = [
        'edit',
        'delete'
    ];

    public function dataTable($model = null)
    {
        $builder = $this->prepareDataTable(Custom::class);
        return $this->dataTableMaker($builder);
    }

    public function save($model = null)
    {
    	$request = $this->getRequest();
    	if (!$model) {
    		$model = new Custom();
    	}

        if ($model) {
            $model->foods()->detach();
        }

    	$model->total = 0;

        if (!$model->save()) {
            return $this->sendErrorResponse($model->errors());
        }

        $total = 0;

        foreach ($request->food as $key => $value) {
        	$food = Food::find($value);
        	$price = $food->price * $request->quantity[$key];
        	$total += $price;
        	$model->foods()->attach($value,['quantity' => $request->quantity[$key],'subtotal' => $price]);
        }

        $model->total = $total;

        if (!$model->save()) {
            return $this->sendErrorResponse($model->errors());
        }
        
        return $this->sendSuccessResponse();
    }

    public function dataTableMaker($builder)
    {    
    	return $builder
            ->addColumn("action", function ($model) {
                return $this->makeActionButtonsForDataTable($model);
            })
            ->addColumn('foods', function($model) {
                $foods = '';
                foreach ($model->foods()->get() as $key => $value) {
                    $foods .= '<p> -'.$value->name.'</p>';
                }
                return $foods;
            })
            ->rawColumns(['action', 'cover','foods','status'])
            ->make(true);
    }

    public function create()
    {
        $view = property_exists($this, 'create_view') ? $this->create_view : $this->form_view;
        $this->attributes['route'] = $this->getFormRoute();

        return $this->render(view($view))->with('food',Food::where('status',1)->pluck('name','id'));
    }

    public function destroy($model)
    {
        if (count($model->purchases()->get()) > 0) {
            return redirect()->back()->withErrors('Cannot delete customs with a purchase');
        }
        $model->foods()->detach();
        if (!$model->delete()) {
            return $this->sendErrorResponse($model->errors());
        }

        return $this->sendSuccessResponse();
    }

    public function edit($model)
    {
        $view = property_exists($this, 'edit_view') ? $this->edit_view : $this->form_view;
        $this->attributes['method'] = 'PUT';
        $this->attributes['route'] = $this->getFormRoute($model);
        return $this->render(view($view), $model)->with('food',Food::where('status',1)->pluck('name','id'))->with('attaches',$model->foods()->get());
    }
}

resources/views/admin/custom/form.blade.php
@extends('admin.base.layout')
@section('title')
Custom
@endsection
@if(empty($model))
    @section('subtitle')
    Create
    @endsection
@else
    @section('subtitle')
    Edit
    @endsection
@endif
@section('top_title')
Custom Form
@endsection
@push('pageRelatedCss')
<style type="text/css">
.btn-circle {
    width: 30px;
    height: 30px;
    padding: 6px 0;
    border-radius: 15px;
    text-align: center;
    font-size: 12px;
    line-height: 1.42857;
}
</style>
@endpush
@section('content')
{!! Form::model($model, [
        'url' => $route,
        'method' => $method,
        'id' => 'demo-form2',
        'class' => 'form-horizontal form-label-left',
        'files' => true,
        'data-parsley-validate'
    ]) !!}
    <div id="food-group">
        @if($model)
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Foods</label>
            
            <div class="row">
                <div class="col-md-5 col-sm-5 col-xs-11">
                   {{ Form::select('food[]', $food, $attaches[0]->id, ['class' => 'foods form-control col-md-7 col-xs-12', 'placeholder' => 'Choose Food','required'=>'required']) }}
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    {{ Form::number('quantity[]', $attaches[0]->pivot->quantity, ['class' => 'quantities form-control', 'placeholder' => 'qty','min'=>'1','id'=>'quantity1']) }}
                </div>
            </div>
            <div id="food-select" class="row">
            @foreach($attaches as $key=>$attach)
            @php
                $number = $key + 1;
            @endphp
            @if($number != 1)
                <div id="food{{$number}}"> 
                    <div  class="col-md-5 col-sm-5 col-xs-11 col-md-offset-3" style="margin-top:10px;">
                    {{ Form::select(
                        'food[]',
                        $food,
                         $attach->id, 
                        ['class' => 'foods form-control col-md-6 col-xs-11', 
                        'placeholder' => 'Choose Food',
                        'required'=>'required']) }}
                    </div>
                <div class="col-md-1 col-sm-1 col-xs-1" style="margin-top:10px;">
                    {{ Form::number('quantity[]', $attach->pivot->quantity, ['class' => 'quantities form-control', 'placeholder' => 'qty','min'=>'1','id'=>'quantity']) }}
                </div>
                <button 
                    type="button" 
                    class="btn btn-circle btn-default col-md-1 col-sm-1 col-xs-1" 
                    style="margin-top:10px"
                    onclick="removeAppend('#food{{$number}}')">&times;</button> 
                </div>
                @endif
            @endforeach
            </div>
        </div>
        {{-- <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Foods</label>
            @foreach($attaches as $key=>$attach)
            @php
                $number = $key + 1;
            @endphp
            @if($number == 1)
            <div class="col-md-6 col-sm-6 col-xs-12">
               {{ Form::select('food[]', $food, $attach->id, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Choose Food','required'=>'required']) }}
            </div>
            @else
            <div id="food-select">
                <div id="food{{$number}}"> 
                    <div  class="col-md-5 col-sm-5 col-xs-11 col-md-offset-3" style="margin-top:10px;">
                    {{ Form::select(
                        'food[]',
                        $food,
                         $attach->id, 
                        ['class' => 'form-control col-md-6 col-xs-11', 
                        'placeholder' => 'Choose Food',
                        'required'=>'required']) }}
                    </div>
                <button 
                    type="button" 
                    class="btn btn-circle btn-default col-md-1 col-sm-1 col-xs-1" 
                    style="margin-top:10px"
                    onclick="removeAppend('#food{{$number}}')">&times;</button> 
                </div>
            </div>
            @endif
            @endforeach
            
            
        </div> --}}
        
        @else
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Foods</label>
            <div class="row">
                <div class="col-md-5 col-sm-5 col-xs-11">
                    {{ Form::select('food[]', $food, null, ['class' => 'foods form-control col-md-7 col-xs-12', 'placeholder' => 'Choose Food','required'=>'required','id'=>'food-sel1']) }}
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    {{ Form::number('quantity[]', 1, ['class' => 'quantities form-control', 'placeholder' => 'qty','min'=>'1','id'=>'quantity1']) }}
                </div>
                <div id="food-select"></div>
            </div>
        </div>
        {{-- /asdfasdfasdf --}}
        {{-- <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Foods</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
               {{ Form::select('food[]', $food, null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Choose Food','required'=>'required']) }}
            </div>
            <div id="food-select"></div>
        </div> --}}
        @endif
        <div class="form-group">
            <a class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3" href="javascript:void(0);" id="add-more">add more</a>
        </div>
        
    </div>
    <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button type="submit" class="btn btn-success pull-right">Submit</button>
        </div>
    </div>
{!! Form::close() !!}

@endsection
@push('pageRelatedJs')
    <script>
        $(document).ready(function () {
            var num = 1;
            $('#add-more').click(function() {
                num += 1;
                $('#food-select').append(`<div class="row" id="food`+num+`"> 
                    <div  class="col-md-5 col-sm-5 col-xs-11 col-md-offset-3" style="margin-top:10px;">
                        {{ Form::select('food[]', $food, null, ['class' => 'foods form-control col-md-6 col-xs-11', 'placeholder' => 'Choose Food','required'=>'required','id'=>'food-sel`+num+`']) }}
                    </div>
                    <div class="col-md-1 col-sm-1 col-xs-1" style="margin-top:10px;">
                        {{ Form::number('quantity[]', 1, ['class' => 'quantities form-control', 'placeholder' => 'qty','min'=>'1','id'=>'quantity`+num+`']) }}
                    </div>
                    <button 
                        type="button" 
                        class="btn btn-circle btn-default col-md-1 col-sm-1 col-xs-1" 
                        style="margin-top:10px"
                        onclick="removeAppend('#food`+num+`')">&times;</button> 
                </div>`);
            })


            // Basic
            $('.dropify').dropify();
            // Translated
            $('.dropify-fr').dropify({
                messages: {
                    default: 'Glissez-déposez un fichier ici ou cliquez'
                    , replace: 'Glissez-déposez un fichier ou cliquez pour remplacer'
                    , remove: 'Supprimer'
                    , error: 'Désolé, le fichier trop volumineux'
                }
            });
            // Used events
            var drEvent = $('#input-file-events').dropify();
            drEvent.on('dropify.beforeClear', function (event, element) {
                return confirm("Do you really want to delete \"" + element.file.name + "\" ?");
            });
            drEvent.on('dropify.afterClear', function (event, element) {
                alert('File deleted');
            });
            drEvent.on('dropify.errors', function (event, element) {
                console.log('Has Errors');
            });
            var drDestroy = $('#input-file-to-destroy').dropify();
            drDestroy = drDestroy.data('dropify')
            $('#toggleDropify').on('click', function (e) {
                e.preventDefault();
                if (drDestroy.isDropified()) {
                    drDestroy.destroy();
                }
                else {
                    drDestroy.init();
                }
            })
        });
        function removeAppend(id) {
            $(id).html('');
        }
    </script>
@endpush

resources/views/admin/custom/index.blade.php
@extends('admin.base.layout')
@section('title')
Customs
@endsection
@section('add_button')
    <a href="{{ route('custom.create') }}" class="btn btn-round btn-info">Add Custom</a>
@endsection
@section('top_title')
Custom Table
@endsection
@section('content')
<table id="type-table" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>No</th>
      <th>Foods</th>
      <th>Total</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
   </tbody>
</table>

@include('shared.delete-modal')
@endsection

@push('pageRelatedJs')
  <script>
    $(document).ready(function () {

      var dataTable = $('#type-table').DataTable({
        dom: 'lfrtip',
        orderCellsTop: true,
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: {
            url:  '{{ route('custom.list') }}',
            data: function(data) {
                data._token = '{{ csrf_token() }}'
            },
            type: 'POST',
        },
        columns: [
            { data: 'id' , name: 'id'},
            { data: 'foods' , name: 'foods', orderable: false, searchable: false },
            { data: 'total' , name: 'total'},
            { data: 'action', name: 'action', orderable: false, searchable: false },

        ],
      })
    });
  </script>
@endpush