routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Models\Slider;
use App\Models\Menu;
Auth::routes();

Route::get('/', function() {
	return view('frontend.homepage')
		->with('sliders',Slider::get())
		->with('menus', Menu::where('status', '=', '1')->limit(4)->orderBy('id', 'desc')
		->get());
})->name('frontend.home');

Route::get('/about',function() {
	return view('frontend.about');
})->name('frontend.about');

Route::get('/contact',function() {
	return view('frontend.contact');
})->name('frontend.contact');

Route::get('/menu',function(){
	$menu = Menu::where('status', '=', '1')->get();
	return view('frontend.menu')->with('menu',$menu);
})->name('frontend.menu');


Route::get('/product/{id}', 'frontendController@toDetails')->name('frontend.product');
Route::get('/menu/custom', 'frontendController@toCustom')->name('frontend.custom');
Route::post('/menu/custom/store', 'frontendController@storeCustom')->name('frontend.store.custom');

Route::get('/cartlist', 'frontendController@cartList')->name('frontend.cartlist');
Route::post('/cart', 'frontendController@addToCart')->name('frontend.add_to_cart');
Route::get('/deleteItem/{rowId}', 'frontendController@removeCart')->name('frontend.remove_cart');
Route::get('/checkout', 'frontendController@checkoutCart')->name('frontend.checkout');
Route::post('/checkout/store', 'frontendController@checkoutStore')->name('frontend.store.checkout');
Route::post('/updateCart', 'frontendController@updateCart')->name('frontend.update');
Route::get('/history', 'frontendController@toHistory')->name('frontend.history');
Route::get('/history/detail/{id}', 'frontendController@historyDetail')->name('frontend.history.detail');

Route::get('/logout','AdminController@logout')->name('logout');
Route::get('/image/{fileName}/{path}','SliderController@getFileByName');
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
	Route::get('/purchase/mark/{model}','PurchaseController@changeStatus');
	Route::get('/receipt','AdminController@goReceipt');
	Route::get('/payment','AdminController@payment');
	Route::get('/purchase/export','PurchaseController@exportData')->name('purchase.export');
	Route::get('/mark/{model}','AdminController@changeStatus');
	Route::get('/receipt/{model}','AdminController@getReceipt');
	Route::post('/menu/calculate','MenuController@calculate');
	Route::post('/dashboard/calculateMenu','AdminController@calculateMenu');
	Route::post('/dashboard/calculateCustom','AdminController@calculateCustom');
	Route::resource('/user', 'UserController');
	Route::resource('/category', 'CategoryController');
	Route::resource('/slider', 'SliderController');
	Route::resource('/food', 'FoodController');
	Route::resource('/menu', 'MenuController');
	Route::resource('/guest', 'GuestController');
	Route::resource('/purchase', 'PurchaseController');
	Route::resource('/custom', 'CustomController');
	Route::resource('/dashboard', 'AdminController');

	Route::group(['prefix' => 'datatable', 'middleware' => ['auth']], function () {
		Route::post('/user', 'UserController@dataTable')->name('user.list');
		Route::post('/category', 'CategoryController@dataTable')->name('category.list');
		Route::post('/slider', 'SliderController@dataTable')->name('slider.list');
		Route::post('/food', 'FoodController@dataTable')->name('food.list');
		Route::post('/menu', 'MenuController@dataTable')->name('menu.list');
		Route::post('/guest', 'GuestController@dataTable')->name('guest.list');
		Route::post('/purchase', 'PurchaseController@dataTable')->name('purchase.list');
		Route::post('/custom', 'CustomController@dataTable')->name('custom.list');
		Route::post('/dashboard', 'AdminController@dataTable')->name('dashboard.list');
	});
});

app/Models/Guest.php
<?php

namespace App\Models;

use App\Models\Base\BaseModel;
use App\Models\Purchase;
use Illuminate\Database\Eloquent\Model;

class Guest extends BaseModel
{
    protected $fillable = [
    	'name','phone','address'
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    public function purchase() {
    	return $this->hasMany(Purchase::class);
    }
}

app/Http/Controllers/GuestController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Guest;
use App\Http\Controllers\MasterController;

class GuestController extends MasterController
{
    protected $show_view = 'admin.guest.index';
    protected $create_view = 'admin.guest.form';
    protected $edit_view = 'admin.guest.form';
    protected $route_bind_model = 'guest'; //Route Model Binding name in RouteServiceProvider
    protected $redirect_when_success = 'guest.index'; //Route Name
    protected $datatable_buttons = [
        'edit',
        'delete'
    ];

    public function dataTable($model = null)
    {
        $builder = $this->prepareDataTable(Guest::class);
        return $this->dataTableMaker($builder);
    }

    public function save($model = null)
    {
        if(!$model) {
            $model = new Guest();
        }
        return $this->saveHandler($model);
    }
}

resources/views/admin/guest/form.blade.php
@extends('admin.base.layout')
@section('title')
Guest
@endsection
@if(empty($model))
    @section('subtitle')
    Create
    @endsection
@else
    @section('subtitle')
    Edit
    @endsection
@endif
@section('top_title')
Guest Form
@endsection

@section('content')
<!-- .row -->
<div class="row">
{!! Form::model($model, [
        'url' => $route,
        'method' => $method,
        'id' => 'demo-form2',
        'class' => 'form-horizontal form-label-left',
        'files' => true,
        'data-parsley-validate'
    ]) !!}
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Name</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            {{ Form::text('name', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Name','required'=>'required']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Phone</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            {{ Form::number('phone', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Phone','required'=>'required']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Address</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            {{ Form::text('address', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Address','required'=>'required']) }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button type="submit" class="btn btn-success pull-right">Submit</button>
        </div>
    </div>
{!! Form::close() !!}
@endsection

resources/views/admin/guest/index.blade.php
@extends('admin.base.layout')
@section('title')
Guests
@endsection
@section('add_button')
    <a href="{{ route('guest.create') }}" class="btn btn-round btn-info">Add Guest</a>
@endsection
@section('top_title')
Guest Table
@endsection
@section('content')
<table id="type-table" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
   </tbody>
</table>

@include('shared.delete-modal')
@endsection

@push('pageRelatedJs')
  <script>
    $(document).ready(function () {

      var dataTable = $('#type-table').DataTable({
        dom: 'lfrtip',
        orderCellsTop: true,
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: {
            url:  '{{ route('guest.list') }}',
            data: function(data) {
                data._token = '{{ csrf_token() }}'
            },
            type: 'POST',
        },
        columns: [
            { data: 'name' , name: 'name'},
            { data: 'phone' , name: 'phone'},
            { data: 'address' , name: 'address'},
            { data: 'action', name: 'action', orderable: false, searchable: false },

        ],
      })
    });
  </script>
@endpush