routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Models\Slider;
use App\Models\Menu;
Auth::routes();

Route::get('/', function() {
	return view('frontend.homepage')
		->with('sliders',Slider::get())
		->with('menus', Menu::where('status', '=', '1')->limit(4)->orderBy('id', 'desc')
		->get());
})->name('frontend.home');

Route::get('/about',function() {
	return view('frontend.about');
})->name('frontend.about');

Route::get('/contact',function() {
	return view('frontend.contact');
})->name('frontend.contact');

Route::get('/menu',function(){
	$menu = Menu::where('status', '=', '1')->get();
	return view('frontend.menu')->with('menu',$menu);
})->name('frontend.menu');


Route::get('/product/{id}', 'frontendController@toDetails')->name('frontend.product');
Route::get('/menu/custom', 'frontendController@toCustom')->name('frontend.custom');
Route::post('/menu/custom/store', 'frontendController@storeCustom')->name('frontend.store.custom');

Route::get('/cartlist', 'frontendController@cartList')->name('frontend.cartlist');
Route::post('/cart', 'frontendController@addToCart')->name('frontend.add_to_cart');
Route::get('/deleteItem/{rowId}', 'frontendController@removeCart')->name('frontend.remove_cart');
Route::get('/checkout', 'frontendController@checkoutCart')->name('frontend.checkout');
Route::post('/checkout/store', 'frontendController@checkoutStore')->name('frontend.store.checkout');
Route::post('/updateCart', 'frontendController@updateCart')->name('frontend.update');
Route::get('/history', 'frontendController@toHistory')->name('frontend.history');
Route::get('/history/detail/{id}', 'frontendController@historyDetail')->name('frontend.history.detail');

Route::get('/logout','AdminController@logout')->name('logout');
Route::get('/image/{fileName}/{path}','SliderController@getFileByName');
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
	Route::get('/purchase/mark/{model}','PurchaseController@changeStatus');
	Route::get('/receipt','AdminController@goReceipt');
	Route::get('/payment','AdminController@payment');
	Route::get('/purchase/export','PurchaseController@exportData')->name('purchase.export');
	Route::get('/mark/{model}','AdminController@changeStatus');
	Route::get('/receipt/{model}','AdminController@getReceipt');
	Route::post('/menu/calculate','MenuController@calculate');
	Route::post('/dashboard/calculateMenu','AdminController@calculateMenu');
	Route::post('/dashboard/calculateCustom','AdminController@calculateCustom');
	Route::resource('/user', 'UserController');
	Route::resource('/category', 'CategoryController');
	Route::resource('/slider', 'SliderController');
	Route::resource('/food', 'FoodController');
	Route::resource('/menu', 'MenuController');
	Route::resource('/guest', 'GuestController');
	Route::resource('/purchase', 'PurchaseController');
	Route::resource('/custom', 'CustomController');
	Route::resource('/dashboard', 'AdminController');

	Route::group(['prefix' => 'datatable', 'middleware' => ['auth']], function () {
		Route::post('/user', 'UserController@dataTable')->name('user.list');
		Route::post('/category', 'CategoryController@dataTable')->name('category.list');
		Route::post('/slider', 'SliderController@dataTable')->name('slider.list');
		Route::post('/food', 'FoodController@dataTable')->name('food.list');
		Route::post('/menu', 'MenuController@dataTable')->name('menu.list');
		Route::post('/guest', 'GuestController@dataTable')->name('guest.list');
		Route::post('/purchase', 'PurchaseController@dataTable')->name('purchase.list');
		Route::post('/custom', 'CustomController@dataTable')->name('custom.list');
		Route::post('/dashboard', 'AdminController@dataTable')->name('dashboard.list');
	});
});

app/Models/Food.php
<?php

namespace App\Models;

use App\Models\Base\BaseModel;
use App\Models\Category;
use App\Models\Custom;
use App\Models\Menu;
use Illuminate\Database\Eloquent\Model;

class Food extends BaseModel
{
    protected $fillable = [
    	'name','price','status','cover','category_id'
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    public function category() {
    	return $this->belongsTo(Category::class,'category_id');
    }

    public function custom() {
    	return $this->belongsToMany(Custom::class);
    }
    public function menu() {
    	return $this->belongsToMany(Menu::class);
    }
}

app/Http/Controllers/FoodController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\MasterController;
use App\Models\Food;
use App\Models\Category;
use Illuminate\Support\Facades\Storage;
use App\Helpers\Enums\StatusEnum;

class FoodController extends MasterController
{
    protected $show_view = 'admin.food.index';
    protected $create_view = 'admin.food.form';
    protected $edit_view = 'admin.food.form';
    protected $route_bind_model = 'food'; //Route Model Binding name in RouteServiceProvider
    protected $redirect_when_success = 'food.index'; //Route Name
    protected $datatable_buttons = [
        'edit',
        'delete'
    ];

    public function create()
    {
        $view = property_exists($this, 'create_view') ? $this->create_view : $this->form_view;
        $this->attributes['route'] = $this->getFormRoute();

        return $this->render(view($view))->with('category',Category::pluck('name','id'));
    }

    public function edit($model)
    {
        $view = property_exists($this, 'edit_view') ? $this->edit_view : $this->form_view;
        $this->attributes['method'] = 'PUT';
        $this->attributes['route'] = $this->getFormRoute($model);
        return $this->render(view($view), $model)->with('category',Category::pluck('name','id'));
    }

    public function dataTable($model = null)
    {
        $builder = $this->prepareDataTable(Food::class);
        return $this->dataTableMaker($builder);
    }


   	public function save($model = null)
    {
    	$request = $this->getRequest();
    	if (!$model) {
    		$model = new Food();
    	}
    	$model->name = $request->name;
    	$model->price = $request->price;
    	$model->category_id = $request->category;
    	$model->status = $request->status;
    	$model->cover = $request->cover ? url('/image/food/'.$this->uploadFiles($request->cover,$model)) : $model->cover;
        if (!$model->save()) {
            return $this->sendErrorResponse($model->errors());
        }
        return $this->sendSuccessResponse();
    }


    //upload photo
    public function uploadFiles($file, $model = null)
    {
        if ($model) {
            if ($model->cover != '' || $model->cover) {
                Storage::delete(Storage_path().'/app/food/'.$model->cover);
            }
        }
    
        return $this->uploadHandler($file);

    }

    public function uploadHandler($file)
    {
        $path = 'food';
    
        if (!Storage::exists($path)) {
            Storage::makeDirectory($path);
        }
    
        $fileName = time().'.'.$file->getClientOriginalExtension();
    
        $file->move(Storage_path().'/app/'.$path, $fileName);
    	
        return $fileName;
    }


    public function dataTableMaker($builder)
    {    
    	return $builder
            ->addColumn("action", function ($model) {
                return $this->makeActionButtonsForDataTable($model);
            })
            ->editColumn('status', function ($model) {
            	if ($model->status == 0) {
                    return '<p style="color:red"> <strong>'.StatusEnum::getString($model->status).'</strong></p>';
                } 
                return '<p style="color:green"> <strong>'.StatusEnum::getString($model->status).'</strong></p>';
            })
            ->editColumn('category_id', function ($model) {
            	return $model->category->name;
            })
            ->editColumn('cover', function ($model) {
            	return '<img src="'.$model->cover.'" style="height:200px;"/>';
            })
            ->rawColumns(['action', 'cover','status'])
            ->make(true);
    }
}

resources/views/admin/food/form.blade.php
@extends('admin.base.layout')
@section('title')
Food
@endsection
@if(empty($model))
    @section('subtitle')
    Create
    @endsection
@else
    @section('subtitle')
    Edit
    @endsection
@endif
@section('top_title')
Food Form
@endsection

@section('content')
{!! Form::model($model, [
        'url' => $route,
        'method' => $method,
        'id' => 'demo-form2',
        'class' => 'form-horizontal form-label-left',
        'files' => true,
        'data-parsley-validate'
    ]) !!}
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Cover</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
              <input 
                    type="file" 
                    name="cover"
                    id="input-file-disable-remove" 
                    class="dropify" 
                    data-show-remove="false" 
                    data-max-file-size="100M"
                    @if($model) 
                        @if($model->cover)  
                            data-default-file="{{ $model->cover }}"
                        @endif
                    @endif
                />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Name</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            {{ Form::text('name', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Name','required'=>'required']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Price</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
           {{ Form::number('price', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Price','required'=>'required','min'=>'0']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Category</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
           {{ Form::select('category', $category, $model ? $model->category_id : null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Choose Category','required'=>'required']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Status</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
           {{ Form::select('status', ['1'=>'active','0'=>'inactive'],null, ['class' => 'form-control col-md-7 col-xs-12','required'=>'required']) }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button type="submit" class="btn btn-success pull-right">Submit</button>
        </div>
    </div>
{!! Form::close() !!}

@endsection
@push('pageRelatedJs')
      <script>
        $(document).ready(function () {
            // Basic
            $('.dropify').dropify();
            // Translated
            $('.dropify-fr').dropify({
                messages: {
                    default: 'Glissez-déposez un fichier ici ou cliquez'
                    , replace: 'Glissez-déposez un fichier ou cliquez pour remplacer'
                    , remove: 'Supprimer'
                    , error: 'Désolé, le fichier trop volumineux'
                }
            });
            // Used events
            var drEvent = $('#input-file-events').dropify();
            drEvent.on('dropify.beforeClear', function (event, element) {
                return confirm("Do you really want to delete \"" + element.file.name + "\" ?");
            });
            drEvent.on('dropify.afterClear', function (event, element) {
                alert('File deleted');
            });
            drEvent.on('dropify.errors', function (event, element) {
                console.log('Has Errors');
            });
            var drDestroy = $('#input-file-to-destroy').dropify();
            drDestroy = drDestroy.data('dropify')
            $('#toggleDropify').on('click', function (e) {
                e.preventDefault();
                if (drDestroy.isDropified()) {
                    drDestroy.destroy();
                }
                else {
                    drDestroy.init();
                }
            })
        });
    </script>
@endpush

resources/views/admin/food/index.blade.php
@extends('admin.base.layout')
@section('title')
Foods
@endsection
@section('add_button')
    <a href="{{ route('food.create') }}" class="btn btn-round btn-info">Add Food</a>
@endsection
@section('top_title')
Food Table
@endsection
@section('content')
<table id="type-table" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Cover</th>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
   </tbody>
</table>

@include('shared.delete-modal')
@endsection

@push('pageRelatedJs')
  <script>
    $(document).ready(function () {

      var dataTable = $('#type-table').DataTable({
        dom: 'lfrtip',
        orderCellsTop: true,
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: {
            url:  '{{ route('food.list') }}',
            data: function(data) {
                data._token = '{{ csrf_token() }}'
            },
            type: 'POST',
        },
        columns: [
            { data: 'cover' , name: 'cover'},
            { data: 'name' , name: 'name'},
            { data: 'price' , name: 'price'},
            { data: 'category_id' , name: 'category_id'},
            { data: 'status' , name: 'status'},
            { data: 'action', name: 'action', orderable: false, searchable: false },

        ],
      })
    });
  </script>
@endpush