routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Models\Slider;
use App\Models\Menu;
Auth::routes();

Route::get('/', function() {
	return view('frontend.homepage')
		->with('sliders',Slider::get())
		->with('menus', Menu::where('status', '=', '1')->limit(4)->orderBy('id', 'desc')
		->get());
})->name('frontend.home');

Route::get('/about',function() {
	return view('frontend.about');
})->name('frontend.about');

Route::get('/contact',function() {
	return view('frontend.contact');
})->name('frontend.contact');

Route::get('/menu',function(){
	$menu = Menu::where('status', '=', '1')->get();
	return view('frontend.menu')->with('menu',$menu);
})->name('frontend.menu');


Route::get('/product/{id}', 'frontendController@toDetails')->name('frontend.product');
Route::get('/menu/custom', 'frontendController@toCustom')->name('frontend.custom');
Route::post('/menu/custom/store', 'frontendController@storeCustom')->name('frontend.store.custom');

Route::get('/cartlist', 'frontendController@cartList')->name('frontend.cartlist');
Route::post('/cart', 'frontendController@addToCart')->name('frontend.add_to_cart');
Route::get('/deleteItem/{rowId}', 'frontendController@removeCart')->name('frontend.remove_cart');
Route::get('/checkout', 'frontendController@checkoutCart')->name('frontend.checkout');
Route::post('/checkout/store', 'frontendController@checkoutStore')->name('frontend.store.checkout');
Route::post('/updateCart', 'frontendController@updateCart')->name('frontend.update');
Route::get('/history', 'frontendController@toHistory')->name('frontend.history');
Route::get('/history/detail/{id}', 'frontendController@historyDetail')->name('frontend.history.detail');

Route::get('/logout','AdminController@logout')->name('logout');
Route::get('/image/{fileName}/{path}','SliderController@getFileByName');
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
	Route::get('/purchase/mark/{model}','PurchaseController@changeStatus');
	Route::get('/receipt','AdminController@goReceipt');
	Route::get('/payment','AdminController@payment');
	Route::get('/purchase/export','PurchaseController@exportData')->name('purchase.export');
	Route::get('/mark/{model}','AdminController@changeStatus');
	Route::get('/receipt/{model}','AdminController@getReceipt');
	Route::post('/menu/calculate','MenuController@calculate');
	Route::post('/dashboard/calculateMenu','AdminController@calculateMenu');
	Route::post('/dashboard/calculateCustom','AdminController@calculateCustom');
	Route::resource('/user', 'UserController');
	Route::resource('/category', 'CategoryController');
	Route::resource('/slider', 'SliderController');
	Route::resource('/food', 'FoodController');
	Route::resource('/menu', 'MenuController');
	Route::resource('/guest', 'GuestController');
	Route::resource('/purchase', 'PurchaseController');
	Route::resource('/custom', 'CustomController');
	Route::resource('/dashboard', 'AdminController');

	Route::group(['prefix' => 'datatable', 'middleware' => ['auth']], function () {
		Route::post('/user', 'UserController@dataTable')->name('user.list');
		Route::post('/category', 'CategoryController@dataTable')->name('category.list');
		Route::post('/slider', 'SliderController@dataTable')->name('slider.list');
		Route::post('/food', 'FoodController@dataTable')->name('food.list');
		Route::post('/menu', 'MenuController@dataTable')->name('menu.list');
		Route::post('/guest', 'GuestController@dataTable')->name('guest.list');
		Route::post('/purchase', 'PurchaseController@dataTable')->name('purchase.list');
		Route::post('/custom', 'CustomController@dataTable')->name('custom.list');
		Route::post('/dashboard', 'AdminController@dataTable')->name('dashboard.list');
	});
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use app\Models\Role;
use app\Models\Purchase;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone','address'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role() {
        return $this->belongsTo(Role::class);
    }

    public function purchase() {
        return $this->belongsTo(Purchase::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\MasterController;
use App\Models\User;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends MasterController
{
    protected $show_view = 'admin.user.index';
    protected $create_view = 'admin.user.form';
    protected $edit_view = 'admin.user.form';
    protected $route_bind_model = 'user'; //Route Model Binding name in RouteServiceProvider
    protected $redirect_when_success = 'user.index'; //Route Name
    protected $datatable_buttons = [
        'edit',
        'delete'
    ];


    public function dataTable($model = null)
    {
        $builder = $this->prepareDataTable(User::class);
        return $this->dataTableMaker($builder);
    }

    public function save($model = null)
    {   

        $request = $this->getRequest();
        $validator = $this->rulesOnCreate($request)->validate();

        if (!$model) {
            $model = new User();
        }
        
        $model->name = $request->name;
        $model->email = $request->email;
        $model->phone = $request->phone;
        $model->address = $request->address;

        
        $model->password = bcrypt($request->password);

        if (!$model->save()) {
            return $this->sendErrorResponse($model->errors());
        }
        $role = Role::find($request->roles);
        $model->assignRole($role->name);

        return $this->sendSuccessResponse();
    }

    public function update($model)
    {
        $request = $this->getRequest();
        $validator = $this->rulesOnUpdate($request)->validate();
        
        $model->name = $request->name;
        $model->email = $request->email;
        $model->phone = $request->phone;
        $model->address = $request->address;

        
        if ($request->password != null) {
            $validator = $this->passwordRulesOnUpdate($request)->validate();
            $model->password = bcrypt($request->password);
        }
       

        if (!$model->save()) {
            return $this->sendErrorResponse($model->errors());
        }
        $role = Role::find($request->roles);
        $model->syncRoles($role->name);

        return $this->sendSuccessResponse();
    }


    public function rulesOnCreate($input)
    {
        $rules = [
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'phone' => 'required',
            'address' => 'required',
            'password' => 'required|min:6',
            'confirm_new_password' => 'required_with:password|same:password'
        ];

        $message = [
            'password.required' => 'Password is required',
            'confirm_new_password.required' => 'Confirm password is required',
            'confirm_new_password.same' => 'Please check your password confirmation'
        ];

        return Validator::make($input->all(), $rules, $message);
    }

    public function rulesOnUpdate($input)
    {
        $rules = [
            'name' => 'required',
            'email' => 'required|email',
            'phone' => 'required',
            'address' => 'required'
        ];

        return Validator::make($input->all(), $rules);
    }

    public function passwordRulesOnUpdate($input)
    {
        $rules = [
            'password' => 'required|min:6',
            'confirm_new_password' => 'required_with:password|same:password'
        ];

        $message = [
            'new_password.required' => 'New password is required',
            'confirm_new_password.required' => 'Confirmation password is required',
            'confirm_new_password.same' => 'Please check your password confirmation'
        ];

        return Validator::make($input->all(), $rules, $message);
    }
}

resources/views/admin/user/form.blade.php
@extends('admin.base.layout')
@section('title')
User
@endsection
@if(empty($model))
    @section('subtitle')
    Create
    @endsection
@else
    @section('subtitle')
    Edit
    @endsection
@endif
@section('top_title')
User Form
@endsection

@section('content')
<!-- .row -->
<div class="row">
{!! Form::model($model, [
        'url' => $route,
        'method' => $method,
        'id' => 'demo-form2',
        'class' => 'form-horizontal form-label-left',
        'files' => true,
        'data-parsley-validate'
    ]) !!}
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Name</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            {{ Form::text('name', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Name','required'=>'required']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Phone</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            {{ Form::number('phone', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Phone number','required'=>'required','min'=>'0']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Email</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            {{ Form::email('email', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Email','required'=>'required']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Address</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            {{ Form::text('address', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Address','required'=>'required']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Role</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            {{ Form::select('roles',
                [
                    "0"=>"admin",
                    "1"=>"user"
                ],
                null,
                ['class' => 'form-control col-md-7 col-xs-12','placeholder'=>'Select Role','required'])
            }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Password</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            @if($model)
            {{ Form::password('password', ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'User Password']) }}
            @else
            {{ Form::password('password', ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'User Password','required'=>'required']) }}
            @endif
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Confirm Password</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            @if($model)
            {{ Form::password('confirm_new_password', ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Confirm Password']) }}
            @else
            {{ Form::password('confirm_new_password', ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Confirm Password','required'=>'required']) }}
            @endif
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button type="submit" class="btn btn-success pull-right">Submit</button>
        </div>
    </div>
{!! Form::close() !!}
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.base.layout')
@section('title')
Users
@endsection
@section('add_button')
    <a href="{{ route('user.create') }}" class="btn btn-round btn-info">Add User</a>
@endsection
@section('top_title')
User Table
@endsection
@section('content')
<table id="type-table" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
   </tbody>
</table>

@include('shared.delete-modal')
@endsection

@push('pageRelatedJs')
  <script>
    $(document).ready(function () {

      var dataTable = $('#type-table').DataTable({
        dom: 'lfrtip',
        orderCellsTop: true,
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: {
            url:  '{{ route('user.list') }}',
            data: function(data) {
                data._token = '{{ csrf_token() }}'
            },
            type: 'POST',
        },
        columns: [
            { data: 'name' , name: 'name'},
            { data: 'email' , name: 'email'},
            { data: 'phone' , name: 'phone'},
            { data: 'address' , name: 'address'},
            { data: 'action', name: 'action', orderable: false, searchable: false },

        ],
      })
    });
  </script>
@endpush